### ISSUE TITLE
Postman Static API Proof (0.75 --> 0.85)

### ISSUE THREAD

**Issue by illuminati1618** [illuminati1618/prism_frontend#11]
## Big Server
![Image](https://github.com/user-attachments/assets/1c627554-47d0-40ce-95d7-53f73cef154f)

![Image](https://github.com/user-attachments/assets/3d23a448-4c59-4ce1-9e23-25c29a455608)

## Little Server

![Image](https://github.com/user-attachments/assets/d73e53fc-0c7d-45c1-a13c-49f5747949ca)

**Comment by CyberLord09** [comment]
![Image](https://github.com/user-attachments/assets/9ee44421-22e9-4535-aa20-e4adf156e65e)

**Comment by manas12709** [comment]
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/95351185-e8fb-4a8a-be49-742072d57e26">

**Comment by adik1025** [comment]
![Image](https://github.com/user-attachments/assets/691043f4-a76f-40d9-b0fa-45adb837ab0e)

**Comment by Hypernova101** [comment]
![Image] (https://ibb.co/PY38Rw3)

**Comment by SanPranav** [comment]
![Image](https://github.com/user-attachments/assets/f371df5a-4f52-4465-a192-58be5979269f)

**Comment by illuminati1618** [comment]
**Yash Parikh**

![Image](https://github.com/user-attachments/assets/d73e53fc-0c7d-45c1-a13c-49f5747949ca)
