### ISSUE TITLE
Initial Planning - 11/20/24

### ISSUE THREAD

**Issue by illuminati1618** [illuminati1618/prism_frontend#2]
# Welcome to **Prism**: Redefining Social Media  
*"A platform that evolves around your connections and creativity."*  

---

## **Introduction**  

Prism transforms traditional social media by fostering **collaborative experiences**, enabling users to craft **dynamic, personalized virtual spaces**, and utilizing **AI-driven enhancements** to create meaningful interactions. On Prism, users don’t merely share moments—they **co-create immersive environments** that embody their relationships, passions, and aspirations.  

### **Brief Summary**  
Prism is a next-generation social media platform where users create customizable "Worlds" to represent their identities, collaborate with others, and connect through shared experiences. Powered by AI and enhanced with interactive storytelling, adaptive aesthetics, and emotional insights, Prism redefines how people interact online by prioritizing creativity, personalization, and meaningful connections.

![Prism Overview](https://i.ibb.co/Jx9k1VG/image.png)

### **Figma Prototype for Prism**

Explore the Prism UI concept on Figma: [Prism UI Idea](https://www.figma.com/design/CPFyDGTMWPwq6d2mZZW8XA/Prism-UI-Idea?node-id=0-1&node-type=canvas&t=xRhPmDnFA0o8sh24-0).

#### **Description of the Figma Prototype**
This Figma design outlines the core user interface (UI) for Prism, showcasing:  
- **Dynamic "Worlds" Pages**: Demonstrates the customizability of user profiles with interactive elements.  
- **Navigation Menus**: Includes conditional menus for authenticated and unauthenticated users.  
- **Sentiment Maps and Storytelling Features**: A visual representation of emotional insights and collaborative story arcs.  
- **Seamless User Experience**: Smooth transitions and intuitive layouts tailored for creativity and connection.  

---

## **Introduction**  

Prism transforms traditional social media by fostering **collaborative experiences**, enabling users to craft **dynamic, personalized virtual spaces**, and utilizing **AI-driven enhancements** to create meaningful interactions. On Prism, users don’t merely share moments—they **co-create immersive environments** that embody their relationships, passions, and aspirations.  

(![Login](https://github.com/user-attachments/assets/0f6deb10-cbc0-4dca-8b36-afe7f6af3c17)

---

## **Team Organization**

| Name              | Role                  | GitHub Profile                                             |
|--------------------|-----------------------|------------------------------------------------------------|
| **Yash**          | Scrum Master          | [illuminati1618/prism_frontend](https://github.com/illuminati1618/prism_frontend) |
| **Anvay**         | Assistant Scrum Master| [CyberLord09/anvay_2025](https://github.com/CyberLord09/anvay_2025) |
| **Mihir**         | Developer             | [Hypernova101/MihirCSP](https://github.com/Hypernova101/MihirCSP) |
| **Adi**           | Developer             | [adik1025/adi_student](https://github.com/adik1025/adi_student) |
| **Manas**         | Developer             | [manas12709/manasg_2025](https://github.com/manas12709/manasg_2025) |
| **Pranav**        | Developer             | [SanPranav/Pranav_2025](https://github.com/SanPranav/Pranav_2025) |
| **Yash (Scrum)**  | Developer             | [illuminati1618/yash_2025](https://github.com/illuminati1618/yash_2025) |

---

## **GitHub Repositories**

| Repository                 | Description                                                        | Link (.io)                                                                        |
|----------------------------|--------------------------------------------------------------------|------------------------------------------------------------------------------|
| **Prism Frontend**         | Frontend for Prism development.                                   | [prism_frontend](https://github.com/illuminati1618/prism_frontend)           |
| **Prism Backend**          | Backend for Prism systems.                                        | [prism_backend](https://github.com/illuminati1618/prism_backend)             |
| **Anvay 2025**             | Assistant Scrum Master contributions, Backend, Frontend, Design. | [Anvay_2025](https://cyberlord09.github.io/anvay_2025/)                      |
| **Mihir CSP**              | Scrum Master, Backend, Frontend, Design.                         | [Mihir_2025](https://hypernova101.github.io/MihirCSP/)                       |
| **Adi Student**            | Scrum Master, Backend.                                           | [Adi_2025](https://adik1025.github.io/adi_student/)                          |
| **Manas G 2025**           | Integrator, All contributions.                                   | [Manas_2025](https://manas12709.github.io/manasg_2025/)                      |
| **Pranav 2025**            | Developer contributions.                                          | [Pranav_2025](https://sanpranav.github.io/Pranav_2025/)                      |
| **Yash 2025**              | Developer and Scrum Master contributions.                        | [Yash_2025](https://illuminati1618.github.io/yash_2025/)                     |

---

### **Scrum Team Focus Areas**  

| Role                     | Key Responsibilities                                                                                         |
|--------------------------|---------------------------------------------------------------------------------------------------------------|
| **Scrum Master**         | Oversee the implementation of interactive Worlds and AI-powered features.                                    |
| **Assistant Scrum Master**| Manage the development of Sentiment Maps and modular storytelling systems.                                  |
| **Developers**           | Focus on specific feature implementations across frontend, backend, and integrations.                        |

### **Interactive Personal Worlds**  
Prism moves beyond static profiles by introducing **"Worlds"**, customizable spaces that reflect users’ identities and connections.  

| Feature                  | Description                                                                                                      |
|--------------------------|------------------------------------------------------------------------------------------------------------------|
| **Customizable Spaces**  | Create digital environments—gardens, museums, or unique landmarks—that celebrate hobbies, milestones, and achievements. |
| **Interactive Design**   | Visitors can explore, leave messages, and interact with objects in these spaces.                                |
| **Group Collaboration**  | Merge Worlds to build shared spaces, such as community hubs or artistic galleries, shaped by collective contributions. |

---

### **AI-Enhanced Interaction**  
Prism’s AI facilitates engaging, natural conversations, bringing users closer through personalized prompts and intelligent insights.  

| Scenario                 | AI-Generated Prompt                                                                                          |
|--------------------------|--------------------------------------------------------------------------------------------------------------|
| Shared Interests: Hiking + Gaming | "Which video game environment reminds you of your favorite hiking trail?"                                    |  

---

### **Storytelling and Social Gaming**  
Prism infuses a narrative layer into the social experience, allowing users to engage with **interactive, adaptive stories**.  

| Feature                   | Description                                                                                                   |
|---------------------------|---------------------------------------------------------------------------------------------------------------|
| **Dynamic Storylines**    | Evolving narratives based on user activity, such as unlocking thematic arcs for specific interests.           |
| **Collaborative Gameplay**| Groups influence shared storylines, creating memorable, collective experiences.                               |  

---

### **Sentiment Visualization**  
Prism’s **Sentiment Maps** blend data visualization with AI to provide emotional insights into posts and interactions.  

| Use Case                 | Benefit                                                                                                       |
|--------------------------|---------------------------------------------------------------------------------------------------------------|
| **Emotional Heatmap**    | Visualize the emotional tone of your network to identify patterns of joy, support, or stress.                |
| **Actionable Insights**  | Reach out to friends posting in "low-energy" zones to offer encouragement and foster positive connections.   |

---

### **Scrum Team Focus Areas**  

| Role                     | Key Responsibilities                                                                                         |
|--------------------------|---------------------------------------------------------------------------------------------------------------|
| **Scrum Master**         | Oversee the implementation of interactive Worlds and AI-powered features.                                    |
| **Assistant Scrum Master**| Manage the development of Sentiment Maps and modular storytelling systems.                                  |

![Scrum Team Organization](https://i.ibb.co/b3nxMLY/image.png)

---

## **Technical Foundation**  

| Component                 | Technology                                                                                                   |
|---------------------------|-------------------------------------------------------------------------------------------------------------|
| **Frontend**              | Data visualizations and interactive features.                                       |
| **Backend**               | Node.js or Python (Flask/Django) for scalable APIs.  (Postman API)                                                      |
| **AI Integration**        | Gemini API or HuggingFace for natural language processing.                                                  |

## *Technical Foundation*

| Component | Technology/Methodology |
|---|---|
| Authentication | JWT stored as a secure cookie, with a fallback in local storage for frontend logic. |
| API Communication | fetch for RESTful API calls to sync user data and maintain session state. |
| Frontend Logic | Event-driven updates using DOMContentLoaded and local storage checks. |
| Backend Validation | Python Flask handles token validation and user authentication. |

---
# **Prism Authentication and Dynamic Sub-Menus**

Prism utilizes **JWT (JSON Web Token)** and **fetch API** for authentication, ensuring that certain features and sub-menus are only available when the user is logged in. Here's a breakdown of the integration:

---

### **Login Conditional Behavior**
1. **Local Storage & JWT Validation**:
   - User authentication status is tracked using `localStorage` and verified through a backend API (`/api/id`) using `fetch`.
   - If the user is not authenticated, requests to fetch user data fail, and public menus remain visible.

2. **Dynamic Menus**:
   - When the user is logged in, the sub-menu dynamically displays options such as `Profile`, `Analytics`, and `Logout`. 
   - If the user is not authenticated, only the `Login` option is visible.

---

#### **`DOMContentLoaded` Event**
The script waits until the DOM is fully loaded to fetch user credentials and update the navigation menu:
```javascript
document.addEventListener('DOMContentLoaded', function() {
    const baseurl = document.querySelector('.trigger').getAttribute('data-baseurl');
    console.log("Base URL:", baseurl); // Debugging line
    getCredentials(baseurl) // Call the function to get credentials
        .then(data => {
            console.log("Credentials data:", data); // Debugging line
            const loginArea = document.getElementById('loginArea');
            if (data) {
                // User authenticated
                loginArea.innerHTML = `
                    <div class="dropdown">
                        <button class="dropbtn">${data.name}</button>
                        <div class="dropdown-content">
                            <a href="${baseurl}/logout">Logout</a>
                            <a href="${baseurl}/profile">Profile</a>
                            <a href="${baseurl}/analytics">Analytics</a>
                        </div>
                    </div>
                `;
            } else {
                // User not authenticated
                loginArea.innerHTML = `<a href="${baseurl}/login">Login</a>`;
            }
        })
        .catch(err => {
            console.error("Error fetching credentials: ", err);
        });
});
```
# Features of the API (myvote API Credit to Anvay Vahia)

## Vote Creation and Updating
- Users can **upvote** or **downvote** a specific post.
- If a vote already exists for the user and post, the vote type is **updated** instead of creating a duplicate.

## Vote Deletion
- Users can **remove their vote** from a post.

## Retrieving Data
The API provides the following data (also depicted in the picture below):
- The number of **upvotes** and **downvotes**.
- Details of each individual **upvote** or **downvote**.

![API](https://i.ibb.co/kHzwM6n/image.png)

# Code Overview

Here’s the main logic of the API:

## Endpoints

1. **POST /vote:**
   - Creates or updates a vote for a specific post.
   - **Example:**
     ```json
     {
       "post_id": 1,
       "vote_type": "upvote"
     }
     ```

2. **DELETE /vote:**
   - Removes a user’s vote from a post.

3. **GET /vote/post:**
   - Retrieves all votes for a post.

## **Why Prism Stands Out**  

| Feature                    | Differentiator                                                                                              |
|----------------------------|------------------------------------------------------------------------------------------------------------|
| **Dynamic Worlds**         | Profiles that evolve with user activity and creativity.                                                   |
| **Narrative Integration**  | Engaging storytelling adds depth to the social experience.                                                |
| **AI-Powered Insights**    | Tools like Sentiment Maps foster meaningful connections.                                                   |
| **Seamless Customization** | Cross-platform compatibility for tailored, immersive experiences.                                         |

---

## **Conceptual Flow**  
![FlowChart](https://i.ibb.co/2ZSL9q0/image-removebg-preview.png)

**Comment by jm1021** [comment]
You have produced a lot of interesting and unique concepts for me.  Create a World sounds interesting, but I would need more of a workflow to understand it.  Same with storyline and gemini interactions.  I like that you are discussing login and guest pages.  It is best if everyone in class sticks to Javascript and Flask/Python, using other stacks causes confusion.  Some of the roles above seems like they could be consolidate.  Not sure you folded in CPT requirements.

In general, I want to support your concepts.  But, I am concerned if you have too much.  But I see a lot of thought and interest in your ideas.   But, perhaps build across ideas strategically so one can be accomplished well, not 3 just in incubation phase.

.92
